version: '3.8'

services:
  api:
    restart: always
    container_name: api
    build:
      context: ./
      dockerfile: Api.Dockerfile
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=development
